name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Install goversioninfo
      run: go install github.com/josephspurrier/goversioninfo/cmd/goversioninfo@latest
    
    - name: Build Windows
      run: |
        cd build
        goversioninfo -o resource.syso versioninfo.json
        GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o koemoji-go.exe ../cmd/koemoji-go
        rm -f resource.syso
    
    - name: Build macOS Intel
      run: |
        cd build
        GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o koemoji-go-darwin-amd64 ../cmd/koemoji-go
    
    - name: Build macOS Apple Silicon
      run: |
        cd build
        GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o koemoji-go-darwin-arm64 ../cmd/koemoji-go
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: koemoji-go-binaries
        path: |
          build/koemoji-go.exe
          build/koemoji-go-darwin-amd64
          build/koemoji-go-darwin-arm64