name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-unix:
    runs-on: ubuntu-latest
    
    env:
      CGO_ENABLED: 1
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libportaudio2 \
          portaudio19-dev \
          libgl1-mesa-dev \
          xorg-dev \
          pkg-config \
    
    - name: Build Linux
      run: |
        cd build
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o koemoji-go-linux-amd64 ../cmd/koemoji-go
    
    - name: Build macOS Intel
      run: |
        cd build
        GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o koemoji-go-darwin-amd64 ../cmd/koemoji-go
    
    - name: Build macOS Apple Silicon
      run: |
        cd build
        GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o koemoji-go-darwin-arm64 ../cmd/koemoji-go
    
    - name: Upload Unix artifacts
      uses: actions/upload-artifact@v4
      with:
        name: koemoji-go-unix-binaries
        path: |
          build/koemoji-go-linux-amd64
          build/koemoji-go-darwin-amd64
          build/koemoji-go-darwin-arm64

  build-windows:
    runs-on: windows-latest
    
    env:
      CGO_ENABLED: 1
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Setup Windows build environment
      run: |
        # Windows環境では、gordonklaus/portaudioパッケージが
        # 必要なDLLを含む可能性があるため、追加のインストールは不要
        echo "Windows build environment ready"
    
    - name: Install goversioninfo
      run: go install github.com/josephspurrier/goversioninfo/cmd/goversioninfo@latest
    
    - name: Build Windows
      run: |
        cd build
        goversioninfo -o resource_windows_amd64.syso versioninfo.json
        Copy-Item resource_windows_amd64.syso ../cmd/koemoji-go/
        go build -ldflags="-s -w" -o koemoji-go.exe ../cmd/koemoji-go
        Remove-Item resource_windows_amd64.syso, ../cmd/koemoji-go/resource_windows_amd64.syso -ErrorAction SilentlyContinue
    
    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v4
      with:
        name: koemoji-go-windows-binaries
        path: |
          build/koemoji-go.exe