name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      CGO_ENABLED: 1
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libportaudio2 \
          libportaudio-dev \
          libgl1-mesa-dev \
          xorg-dev \
          pkg-config \
          gcc-mingw-w64
    
    - name: Install goversioninfo
      run: go install github.com/josephspurrier/goversioninfo/cmd/goversioninfo@latest
    
    - name: Build Windows
      env:
        CC: x86_64-w64-mingw32-gcc
        CXX: x86_64-w64-mingw32-g++
      run: |
        cd build
        goversioninfo -o resource_windows_amd64.syso versioninfo.json
        cp resource_windows_amd64.syso ../cmd/koemoji-go/
        GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o koemoji-go.exe ../cmd/koemoji-go
        rm -f resource_windows_amd64.syso ../cmd/koemoji-go/resource_windows_amd64.syso
    
    - name: Build macOS Intel
      run: |
        cd build
        GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o koemoji-go-darwin-amd64 ../cmd/koemoji-go
    
    - name: Build macOS Apple Silicon
      run: |
        cd build
        GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o koemoji-go-darwin-arm64 ../cmd/koemoji-go
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: koemoji-go-binaries
        path: |
          build/koemoji-go.exe
          build/koemoji-go-darwin-amd64
          build/koemoji-go-darwin-arm64